FROM php:7

RUN mkdir /var/www
WORKDIR /var/www

RUN apt-get update -y \
  && apt-get install -y \
  openssl \
  zip \
  unzip \
  git \
  && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer \
  && docker-php-ext-install pdo pdo_mysql mbstring

COPY . /var/www
RUN composer install

CMD ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]
