FROM php:7

RUN mkdir /var/www
WORKDIR /var/www

RUN apt-get update -y \
  && apt-get install -y \
    openssl \
    zip \
    unzip \
    git \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    libpng12-dev \
    \
    && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer \
   	&& docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
   	&& docker-php-ext-install pdo pdo_mysql mbstring gd

COPY . /var/www
RUN composer install

CMD ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]
