<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateTipoEnderecoTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
      Schema::create('TypeStreet', function (Blueprint $table) {
        $table->integer("id")->unsigned();
        $table->string("name", 40);
        $table->primary("id");
      });
      DB::Table('TypeStreet')->insert(array('id' => 1, 'name' => 'Beco'));
      DB::Table('TypeStreet')->insert(array('id' => 2, 'name' => 'Rua'));
      DB::Table('TypeStreet')->insert(array('id' => 3, 'name' => 'Travessa'));
      DB::Table('TypeStreet')->insert(array('id' => 4, 'name' => 'Avenida'));
      DB::Table('TypeStreet')->insert(array('id' => 5, 'name' => 'Praça'));
      DB::Table('TypeStreet')->insert(array('id' => 6, 'name' => 'Canal'));
      DB::Table('TypeStreet')->insert(array('id' => 7, 'name' => 'Estrada'));
      DB::Table('TypeStreet')->insert(array('id' => 8, 'name' => 'Parque'));
      DB::Table('TypeStreet')->insert(array('id' => 9, 'name' => 'Mercado'));
      DB::Table('TypeStreet')->insert(array('id' => 10, 'name' => 'Rodovia'));
      DB::Table('TypeStreet')->insert(array('id' => 11, 'name' => 'Ramal'));
      DB::Table('TypeStreet')->insert(array('id' => 12, 'name' => 'Via'));
      DB::Table('TypeStreet')->insert(array('id' => 13, 'name' => 'Alameda'));
      DB::Table('TypeStreet')->insert(array('id' => 14, 'name' => 'Área'));
      DB::Table('TypeStreet')->insert(array('id' => 15, 'name' => 'Largo'));
      DB::Table('TypeStreet')->insert(array('id' => 16, 'name' => 'Vila'));
      DB::Table('TypeStreet')->insert(array('id' => 17, 'name' => 'Loteamento'));
      DB::Table('TypeStreet')->insert(array('id' => 18, 'name' => 'Parque Municipal'));
      DB::Table('TypeStreet')->insert(array('id' => 19, 'name' => 'Conjunto'));
      DB::Table('TypeStreet')->insert(array('id' => 20, 'name' => 'Condomínio'));
      DB::Table('TypeStreet')->insert(array('id' => 21, 'name' => '2ª Travessa'));
      DB::Table('TypeStreet')->insert(array('id' => 22, 'name' => '3ª Travessa'));
      DB::Table('TypeStreet')->insert(array('id' => 23, 'name' => 'Condomínio Residencial'));
      DB::Table('TypeStreet')->insert(array('id' => 24, 'name' => '1ª Travessa'));
      DB::Table('TypeStreet')->insert(array('id' => 25, 'name' => '2ª Rua'));
      DB::Table('TypeStreet')->insert(array('id' => 26, 'name' => '1ª Rua'));
      DB::Table('TypeStreet')->insert(array('id' => 27, 'name' => '3ª Rua'));
      DB::Table('TypeStreet')->insert(array('id' => 28, 'name' => 'Quadra'));
      DB::Table('TypeStreet')->insert(array('id' => 29, 'name' => '4ª Travessa'));
      DB::Table('TypeStreet')->insert(array('id' => 30, 'name' => 'Ladeira'));
      DB::Table('TypeStreet')->insert(array('id' => 31, 'name' => '6ª Travessa'));
      DB::Table('TypeStreet')->insert(array('id' => 32, 'name' => '7ª Travessa'));
      DB::Table('TypeStreet')->insert(array('id' => 33, 'name' => '8ª Travessa'));
      DB::Table('TypeStreet')->insert(array('id' => 34, 'name' => '5ª Travessa'));
      DB::Table('TypeStreet')->insert(array('id' => 35, 'name' => 'Escadaria'));
      DB::Table('TypeStreet')->insert(array('id' => 36, 'name' => 'Conjunto Residencial'));
      DB::Table('TypeStreet')->insert(array('id' => 37, 'name' => 'Parque Residencial'));
      DB::Table('TypeStreet')->insert(array('id' => 38, 'name' => 'Residencial'));
      DB::Table('TypeStreet')->insert(array('id' => 39, 'name' => 'Vale'));
      DB::Table('TypeStreet')->insert(array('id' => 40, 'name' => '4ª Rua'));
      DB::Table('TypeStreet')->insert(array('id' => 41, 'name' => '5ª Rua'));
      DB::Table('TypeStreet')->insert(array('id' => 42, 'name' => '10ª Travessa'));
      DB::Table('TypeStreet')->insert(array('id' => 43, 'name' => '11ª Travessa'));
      DB::Table('TypeStreet')->insert(array('id' => 44, 'name' => '9ª Travessa'));
      DB::Table('TypeStreet')->insert(array('id' => 45, 'name' => '12ª Travessa'));
      DB::Table('TypeStreet')->insert(array('id' => 46, 'name' => '13ª Travessa'));
      DB::Table('TypeStreet')->insert(array('id' => 47, 'name' => '14ª Travessa'));
      DB::Table('TypeStreet')->insert(array('id' => 48, 'name' => '15ª Travessa'));
      DB::Table('TypeStreet')->insert(array('id' => 49, 'name' => 'Bloco'));
      DB::Table('TypeStreet')->insert(array('id' => 50, 'name' => '16ª Travessa'));
      DB::Table('TypeStreet')->insert(array('id' => 51, 'name' => '17ª Travessa'));
      DB::Table('TypeStreet')->insert(array('id' => 52, 'name' => '18ª Travessa'));
      DB::Table('TypeStreet')->insert(array('id' => 53, 'name' => '19ª Travessa'));
      DB::Table('TypeStreet')->insert(array('id' => 54, 'name' => '20ª Travessa'));
      DB::Table('TypeStreet')->insert(array('id' => 55, 'name' => '21ª Travessa'));
      DB::Table('TypeStreet')->insert(array('id' => 56, 'name' => '22ª Travessa'));
      DB::Table('TypeStreet')->insert(array('id' => 57, 'name' => 'Boulevard'));
      DB::Table('TypeStreet')->insert(array('id' => 58, 'name' => 'Margem'));
      DB::Table('TypeStreet')->insert(array('id' => 59, 'name' => 'Jardim'));
      DB::Table('TypeStreet')->insert(array('id' => 60, 'name' => 'Bosque'));
      DB::Table('TypeStreet')->insert(array('id' => 61, 'name' => 'Acesso'));
      DB::Table('TypeStreet')->insert(array('id' => 62, 'name' => 'Passagem'));
      DB::Table('TypeStreet')->insert(array('id' => 63, 'name' => 'Campo'));
      DB::Table('TypeStreet')->insert(array('id' => 64, 'name' => 'Rampa'));
      DB::Table('TypeStreet')->insert(array('id' => 65, 'name' => 'Passarela'));
      DB::Table('TypeStreet')->insert(array('id' => 66, 'name' => '1ª Avenida'));
      DB::Table('TypeStreet')->insert(array('id' => 67, 'name' => '2ª Avenida'));
      DB::Table('TypeStreet')->insert(array('id' => 68, 'name' => '3ª Avenida'));
      DB::Table('TypeStreet')->insert(array('id' => 69, 'name' => '1ª Travessa da Rodovia'));
      DB::Table('TypeStreet')->insert(array('id' => 70, 'name' => '2ª Travessa da Rodovia'));
      DB::Table('TypeStreet')->insert(array('id' => 71, 'name' => 'Baixa'));
      DB::Table('TypeStreet')->insert(array('id' => 72, 'name' => 'Comunidade'));
      DB::Table('TypeStreet')->insert(array('id' => 73, 'name' => 'Alto'));
      DB::Table('TypeStreet')->insert(array('id' => 74, 'name' => 'Viela'));
      DB::Table('TypeStreet')->insert(array('id' => 75, 'name' => 'Marginal'));
      DB::Table('TypeStreet')->insert(array('id' => 76, 'name' => 'Favela'));
      DB::Table('TypeStreet')->insert(array('id' => 77, 'name' => 'Caminho'));
      DB::Table('TypeStreet')->insert(array('id' => 78, 'name' => 'Passeio'));
      DB::Table('TypeStreet')->insert(array('id' => 79, 'name' => 'Via Local'));
      DB::Table('TypeStreet')->insert(array('id' => 80, 'name' => 'Via Pedestre'));
      DB::Table('TypeStreet')->insert(array('id' => 81, 'name' => 'Via Lateral'));
      DB::Table('TypeStreet')->insert(array('id' => 82, 'name' => 'Via Principal'));
      DB::Table('TypeStreet')->insert(array('id' => 83, 'name' => 'Estrada Velha'));
      DB::Table('TypeStreet')->insert(array('id' => 84, 'name' => 'Corredor'));
      DB::Table('TypeStreet')->insert(array('id' => 85, 'name' => 'Estrada Antiga'));
      DB::Table('TypeStreet')->insert(array('id' => 86, 'name' => '4ª Avenida'));
      DB::Table('TypeStreet')->insert(array('id' => 87, 'name' => 'Beco 1'));
      DB::Table('TypeStreet')->insert(array('id' => 88, 'name' => 'Beco 2'));
      DB::Table('TypeStreet')->insert(array('id' => 89, 'name' => 'Beco 3'));
      DB::Table('TypeStreet')->insert(array('id' => 90, 'name' => 'Escada'));
      DB::Table('TypeStreet')->insert(array('id' => 91, 'name' => 'Rótula'));
      DB::Table('TypeStreet')->insert(array('id' => 92, 'name' => 'Rua Principal'));
      DB::Table('TypeStreet')->insert(array('id' => 93, 'name' => 'Estrada de Ferro'));
      DB::Table('TypeStreet')->insert(array('id' => 94, 'name' => 'Túnel'));
      DB::Table('TypeStreet')->insert(array('id' => 95, 'name' => 'Estação'));
      DB::Table('TypeStreet')->insert(array('id' => 96, 'name' => '1ª Vila'));
      DB::Table('TypeStreet')->insert(array('id' => 97, 'name' => 'Rua de Ligação'));
      DB::Table('TypeStreet')->insert(array('id' => 98, 'name' => '26ª Travessa'));
      DB::Table('TypeStreet')->insert(array('id' => 99, 'name' => '1ª Ladeira'));
      DB::Table('TypeStreet')->insert(array('id' => 100, 'name' => '2ª Ladeira'));
      DB::Table('TypeStreet')->insert(array('id' => 101, 'name' => '3ª Ladeira'));
      DB::Table('TypeStreet')->insert(array('id' => 102, 'name' => '2ª Vila'));
      DB::Table('TypeStreet')->insert(array('id' => 103, 'name' => '3ª Vila'));
      DB::Table('TypeStreet')->insert(array('id' => 104, 'name' => '5ª Vila'));
      DB::Table('TypeStreet')->insert(array('id' => 105, 'name' => '5ª Avenida'));
      DB::Table('TypeStreet')->insert(array('id' => 106, 'name' => '4ª Vila'));
      DB::Table('TypeStreet')->insert(array('id' => 107, 'name' => '6ª Avenida'));
      DB::Table('TypeStreet')->insert(array('id' => 108, 'name' => '11ª Avenida'));
      DB::Table('TypeStreet')->insert(array('id' => 109, 'name' => '10ª Avenida'));
      DB::Table('TypeStreet')->insert(array('id' => 110, 'name' => '9ª Avenida'));
      DB::Table('TypeStreet')->insert(array('id' => 111, 'name' => '7ª Avenida'));
      DB::Table('TypeStreet')->insert(array('id' => 112, 'name' => '8ª Avenida'));
      DB::Table('TypeStreet')->insert(array('id' => 113, 'name' => 'Feira'));
      DB::Table('TypeStreet')->insert(array('id' => 114, 'name' => 'Fazenda'));
      DB::Table('TypeStreet')->insert(array('id' => 115, 'name' => '2ª Subida'));
      DB::Table('TypeStreet')->insert(array('id' => 116, 'name' => 'Chácara'));
      DB::Table('TypeStreet')->insert(array('id' => 117, 'name' => 'Acesso Local'));
      DB::Table('TypeStreet')->insert(array('id' => 118, 'name' => 'Via Coletora'));
      DB::Table('TypeStreet')->insert(array('id' => 119, 'name' => 'Terminal'));
      DB::Table('TypeStreet')->insert(array('id' => 120, 'name' => 'Colina'));
      DB::Table('TypeStreet')->insert(array('id' => 121, 'name' => 'Setor'));
      DB::Table('TypeStreet')->insert(array('id' => 122, 'name' => 'Área Verde'));
      DB::Table('TypeStreet')->insert(array('id' => 123, 'name' => 'Rua de Pedestre'));
      DB::Table('TypeStreet')->insert(array('id' => 124, 'name' => 'Galeria'));
      DB::Table('TypeStreet')->insert(array('id' => 125, 'name' => 'Contorno'));
      DB::Table('TypeStreet')->insert(array('id' => 126, 'name' => 'Praia'));
      DB::Table('TypeStreet')->insert(array('id' => 127, 'name' => 'Via de Pedestre'));
      DB::Table('TypeStreet')->insert(array('id' => 128, 'name' => 'Calçadão'));
      DB::Table('TypeStreet')->insert(array('id' => 129, 'name' => 'Esplanada'));
      DB::Table('TypeStreet')->insert(array('id' => 130, 'name' => 'Trecho'));
      DB::Table('TypeStreet')->insert(array('id' => 131, 'name' => 'Acampamento'));
      DB::Table('TypeStreet')->insert(array('id' => 132, 'name' => 'Área Especial'));
      DB::Table('TypeStreet')->insert(array('id' => 133, 'name' => 'Granja'));
      DB::Table('TypeStreet')->insert(array('id' => 134, 'name' => 'Colônia'));
      DB::Table('TypeStreet')->insert(array('id' => 135, 'name' => 'Núcleo Rural'));
      DB::Table('TypeStreet')->insert(array('id' => 136, 'name' => 'Núcleo'));
      DB::Table('TypeStreet')->insert(array('id' => 137, 'name' => 'Entre Quadra'));
      DB::Table('TypeStreet')->insert(array('id' => 138, 'name' => 'Aeroporto'));
      DB::Table('TypeStreet')->insert(array('id' => 139, 'name' => 'Sítio'));
      DB::Table('TypeStreet')->insert(array('id' => 140, 'name' => 'Módulo'));
      DB::Table('TypeStreet')->insert(array('id' => 141, 'name' => 'Campus'));
      DB::Table('TypeStreet')->insert(array('id' => 142, 'name' => 'Ponte'));
      DB::Table('TypeStreet')->insert(array('id' => 143, 'name' => 'Edifício'));
      DB::Table('TypeStreet')->insert(array('id' => 144, 'name' => 'Eixo Industrial'));
      DB::Table('TypeStreet')->insert(array('id' => 145, 'name' => 'Circular'));
      DB::Table('TypeStreet')->insert(array('id' => 146, 'name' => 'Pátio'));
      DB::Table('TypeStreet')->insert(array('id' => 147, 'name' => 'Servidão'));
      DB::Table('TypeStreet')->insert(array('id' => 148, 'name' => 'Antiga Estação'));
      DB::Table('TypeStreet')->insert(array('id' => 149, 'name' => 'Recanto'));
      DB::Table('TypeStreet')->insert(array('id' => 150, 'name' => '1º Alto'));
      DB::Table('TypeStreet')->insert(array('id' => 151, 'name' => 'Via de Acesso'));
      DB::Table('TypeStreet')->insert(array('id' => 152, 'name' => 'Via Expressa'));
      DB::Table('TypeStreet')->insert(array('id' => 153, 'name' => 'Pista Lateral'));
      DB::Table('TypeStreet')->insert(array('id' => 154, 'name' => 'Eixo'));
      DB::Table('TypeStreet')->insert(array('id' => 155, 'name' => 'Eixo Principal'));
      DB::Table('TypeStreet')->insert(array('id' => 156, 'name' => 'Rua Vicinal'));
      DB::Table('TypeStreet')->insert(array('id' => 157, 'name' => 'Atalho'));
      DB::Table('TypeStreet')->insert(array('id' => 158, 'name' => 'Trevo'));
      DB::Table('TypeStreet')->insert(array('id' => 159, 'name' => 'Desvio'));
      DB::Table('TypeStreet')->insert(array('id' => 160, 'name' => 'Estádio'));
      DB::Table('TypeStreet')->insert(array('id' => 161, 'name' => 'Gleba'));
      DB::Table('TypeStreet')->insert(array('id' => 162, 'name' => 'Estrada Municipal'));
      DB::Table('TypeStreet')->insert(array('id' => 163, 'name' => 'Distrito'));
      DB::Table('TypeStreet')->insert(array('id' => 164, 'name' => 'Rua Projetada'));
      DB::Table('TypeStreet')->insert(array('id' => 165, 'name' => 'Avenida Perimetral'));
      DB::Table('TypeStreet')->insert(array('id' => 166, 'name' => 'Fonte'));
      DB::Table('TypeStreet')->insert(array('id' => 167, 'name' => 'Avenida Contorno'));
      DB::Table('TypeStreet')->insert(array('id' => 168, 'name' => 'Ciclovia'));
      DB::Table('TypeStreet')->insert(array('id' => 169, 'name' => 'Porto'));
      DB::Table('TypeStreet')->insert(array('id' => 170, 'name' => 'Retorno'));
      DB::Table('TypeStreet')->insert(array('id' => 171, 'name' => 'Córrego'));
      DB::Table('TypeStreet')->insert(array('id' => 172, 'name' => 'Via de Pedestres'));
      DB::Table('TypeStreet')->insert(array('id' => 173, 'name' => 'Viaduto'));
      DB::Table('TypeStreet')->insert(array('id' => 174, 'name' => 'Antiga Estrada'));
      DB::Table('TypeStreet')->insert(array('id' => 175, 'name' => 'Passagem de Pedestres'));
      DB::Table('TypeStreet')->insert(array('id' => 176, 'name' => 'Complexo Viário'));
      DB::Table('TypeStreet')->insert(array('id' => 177, 'name' => 'Anel Viário'));
      DB::Table('TypeStreet')->insert(array('id' => 178, 'name' => 'Avenida Marginal Direita'));
      DB::Table('TypeStreet')->insert(array('id' => 179, 'name' => 'Avenida Marginal Esquerda'));
      DB::Table('TypeStreet')->insert(array('id' => 180, 'name' => 'Prolongamento'));
      DB::Table('TypeStreet')->insert(array('id' => 181, 'name' => 'Vereda'));
      DB::Table('TypeStreet')->insert(array('id' => 182, 'name' => 'Lagoa'));
      DB::Table('TypeStreet')->insert(array('id' => 183, 'name' => 'Rotatória'));
      DB::Table('TypeStreet')->insert(array('id' => 184, 'name' => 'Avenida Marginal'));
      DB::Table('TypeStreet')->insert(array('id' => 185, 'name' => 'Artéria'));
      DB::Table('TypeStreet')->insert(array('id' => 186, 'name' => 'Ilha'));
      DB::Table('TypeStreet')->insert(array('id' => 187, 'name' => 'Via Litorânea'));
      DB::Table('TypeStreet')->insert(array('id' => 188, 'name' => 'Subida'));
      DB::Table('TypeStreet')->insert(array('id' => 189, 'name' => '2º Beco'));
      DB::Table('TypeStreet')->insert(array('id' => 190, 'name' => '1ª Paralela'));
      DB::Table('TypeStreet')->insert(array('id' => 191, 'name' => '2ª Paralela'));
      DB::Table('TypeStreet')->insert(array('id' => 192, 'name' => '2º Alto'));
      DB::Table('TypeStreet')->insert(array('id' => 193, 'name' => '6ª Rua'));
      DB::Table('TypeStreet')->insert(array('id' => 194, 'name' => '3º Alto'));
      DB::Table('TypeStreet')->insert(array('id' => 195, 'name' => 'Descida'));
      DB::Table('TypeStreet')->insert(array('id' => 196, 'name' => 'Rua Velha'));
      DB::Table('TypeStreet')->insert(array('id' => 197, 'name' => 'Paralela'));
      DB::Table('TypeStreet')->insert(array('id' => 198, 'name' => '4ª Paralela'));
      DB::Table('TypeStreet')->insert(array('id' => 199, 'name' => '3ª Paralela'));
      DB::Table('TypeStreet')->insert(array('id' => 200, 'name' => 'Cais'));
      DB::Table('TypeStreet')->insert(array('id' => 201, 'name' => '1º Beco'));
      DB::Table('TypeStreet')->insert(array('id' => 202, 'name' => '3º Beco'));
      DB::Table('TypeStreet')->insert(array('id' => 203, 'name' => '1ª Subida'));
      DB::Table('TypeStreet')->insert(array('id' => 204, 'name' => '3ª Subida'));
      DB::Table('TypeStreet')->insert(array('id' => 205, 'name' => '6ª Subida'));
      DB::Table('TypeStreet')->insert(array('id' => 206, 'name' => '5ª Subida'));
      DB::Table('TypeStreet')->insert(array('id' => 207, 'name' => '4ª Subida'));
      DB::Table('TypeStreet')->insert(array('id' => 208, 'name' => 'Unidade'));
      DB::Table('TypeStreet')->insert(array('id' => 209, 'name' => 'Via Marginal'));
      DB::Table('TypeStreet')->insert(array('id' => 210, 'name' => 'Trincheira'));
      DB::Table('TypeStreet')->insert(array('id' => 211, 'name' => 'Jardinete'));
      DB::Table('TypeStreet')->insert(array('id' => 212, 'name' => 'Estrada Nova'));
      DB::Table('TypeStreet')->insert(array('id' => 213, 'name' => 'Morro'));
      DB::Table('TypeStreet')->insert(array('id' => 214, 'name' => 'Ponta'));
      DB::Table('TypeStreet')->insert(array('id' => 215, 'name' => 'Quinta'));
      DB::Table('TypeStreet')->insert(array('id' => 216, 'name' => 'Variante da Estrada'));
      DB::Table('TypeStreet')->insert(array('id' => 217, 'name' => 'Vala'));
      DB::Table('TypeStreet')->insert(array('id' => 218, 'name' => 'Outeiro'));
      DB::Table('TypeStreet')->insert(array('id' => 219, 'name' => 'Forte'));
      DB::Table('TypeStreet')->insert(array('id' => 220, 'name' => 'Parada'));
      DB::Table('TypeStreet')->insert(array('id' => 221, 'name' => 'Adro'));
      DB::Table('TypeStreet')->insert(array('id' => 222, 'name' => 'Zigue-Zague'));
      DB::Table('TypeStreet')->insert(array('id' => 223, 'name' => 'Servidão de Passagem'));
      DB::Table('TypeStreet')->insert(array('id' => 224, 'name' => 'Entrada Particular'));
      DB::Table('TypeStreet')->insert(array('id' => 225, 'name' => 'Caminho de Servidão'));
      DB::Table('TypeStreet')->insert(array('id' => 226, 'name' => 'Reta'));
      DB::Table('TypeStreet')->insert(array('id' => 227, 'name' => 'Buraco'));
      DB::Table('TypeStreet')->insert(array('id' => 228, 'name' => 'Travessa Particular'));
      DB::Table('TypeStreet')->insert(array('id' => 229, 'name' => 'Via Costeira'));
      DB::Table('TypeStreet')->insert(array('id' => 230, 'name' => 'Belvedere'));
      DB::Table('TypeStreet')->insert(array('id' => 231, 'name' => 'Elevada'));
      DB::Table('TypeStreet')->insert(array('id' => 232, 'name' => 'Acesso Estadual'));
      DB::Table('TypeStreet')->insert(array('id' => 233, 'name' => 'Estacionamento'));
      DB::Table('TypeStreet')->insert(array('id' => 234, 'name' => 'Escada de Pedra'));
      DB::Table('TypeStreet')->insert(array('id' => 235, 'name' => 'Conjunto Habitacional'));
      DB::Table('TypeStreet')->insert(array('id' => 236, 'name' => 'Estrada de Servidão'));
      DB::Table('TypeStreet')->insert(array('id' => 237, 'name' => 'Rodovia Municipal'));
      DB::Table('TypeStreet')->insert(array('id' => 238, 'name' => 'Estrada Vicinal'));
      DB::Table('TypeStreet')->insert(array('id' => 239, 'name' => 'Rodo Anel'));
      DB::Table('TypeStreet')->insert(array('id' => 240, 'name' => 'Lago'));
      DB::Table('TypeStreet')->insert(array('id' => 241, 'name' => 'Estrada Estadual'));
      DB::Table('TypeStreet')->insert(array('id' => 242, 'name' => 'Praça de Esportes'));
      DB::Table('TypeStreet')->insert(array('id' => 243, 'name' => 'Terceira Avenida'));
      DB::Table('TypeStreet')->insert(array('id' => 244, 'name' => 'Calçada'));
      DB::Table('TypeStreet')->insert(array('id' => 245, 'name' => 'Variante'));
      DB::Table('TypeStreet')->insert(array('id' => 246, 'name' => 'Estrada Particular'));
      DB::Table('TypeStreet')->insert(array('id' => 247, 'name' => 'Ruela'));
      DB::Table('TypeStreet')->insert(array('id' => 248, 'name' => 'Estrada Vicinal Municipal'));
      DB::Table('TypeStreet')->insert(array('id' => 249, 'name' => 'Rua Particular'));
      DB::Table('TypeStreet')->insert(array('id' => 250, 'name' => 'Monte'));
      DB::Table('TypeStreet')->insert(array('id' => 251, 'name' => 'Estrada Intermunicipal'));
      DB::Table('TypeStreet')->insert(array('id' => 252, 'name' => 'Passeio Público'));
      DB::Table('TypeStreet')->insert(array('id' => 253, 'name' => 'Avenida Marginal Norte'));
      DB::Table('TypeStreet')->insert(array('id' => 254, 'name' => 'Núcleo Habitacional'));
      DB::Table('TypeStreet')->insert(array('id' => 255, 'name' => 'Balão'));
      DB::Table('TypeStreet')->insert(array('id' => 256, 'name' => 'Alça de Acesso'));
      DB::Table('TypeStreet')->insert(array('id' => 257, 'name' => 'Blocos'));
      DB::Table('TypeStreet')->insert(array('id' => 258, 'name' => 'Bulevar'));
      DB::Table('TypeStreet')->insert(array('id' => 259, 'name' => 'Passagem Subterrânea'));
      DB::Table('TypeStreet')->insert(array('id' => 260, 'name' => 'Estrada Ecoturística'));
      DB::Table('TypeStreet')->insert(array('id' => 261, 'name' => 'Jardim Residencial'));
      DB::Table('TypeStreet')->insert(array('id' => 262, 'name' => 'Estrada de Ligação'));

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('TypeStreet');
    }
}
